# Generated by Django 5.2 on 2025-08-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_product_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceProducts',
        ),
    ]
