# Generated by Django 5.2 on 2025-08-27 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lateness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lateness_type', models.CharField(choices=[('work_start', 'Work Start'), ('lunch_return', 'Lunch Return')], max_length=20)),
                ('minutes_late', models.PositiveIntegerField(default=0)),
                ('lives_used', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'lateness',
                'ordering': ['-date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeLatenessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_lives', models.PositiveSmallIntegerField(default=3)),
                ('lives_remaining', models.PositiveSmallIntegerField(default=3)),
                ('total_minutes_late', models.PositiveIntegerField(default=0)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'employee_lateness_summaries',
                'managed': True,
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
