# Generated by Django 5.2 on 2025-08-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_employee_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('back_to', models.TimeField(blank=True, null=True)),
                ('calculated_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('late_minutes', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'db_table': 'lunches',
                'managed': True,
            },
        ),
    ]
