# Generated by Django 5.2 on 2025-08-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='calculated_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='late_minutes',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
