# Generated by Django 5.2 on 2025-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeincident',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
