# Generated by Django 5.2 on 2025-08-16 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('customers', '0002_alter_customer_names'),
        ('products', '0004_priceproducts_alter_product_description'),
        ('warehouses', '0002_warehouse_company_or_branch_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=8)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quote_status', models.CharField(choices=[('issued', 'Issued'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='issued', max_length=20)),
                ('migrate_quote', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_approved', to=settings.AUTH_USER_MODEL)),
                ('canceled_by', models.ForeignKey(blank=True, db_column='canceled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_canceled', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='currencies.currency')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='customers.customer')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, db_column='warehouse_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'quotes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_method', models.BooleanField(default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='quote_details', to='products.product')),
                ('quote', models.ForeignKey(db_column='quote_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotes.quote')),
            ],
            options={
                'db_table': 'quote_details',
                'managed': True,
            },
        ),
    ]
