# Generated by Django 5.2 on 2025-08-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_delete_priceproducts'),
        ('warehouses', '0002_warehouse_company_or_branch_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('current_booking', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_controls', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_controls', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_controls', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_controls', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_control',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('current_stock__gte', 0)), name='chk_current_stock_gte_0'), models.CheckConstraint(condition=models.Q(('current_booking__gte', 0)), name='chk_current_booking_gte_0'), models.CheckConstraint(condition=models.Q(('max_stock__gt', models.F('min_stock'))), name='chk_max_stock_gt_min_stock')],
            },
        ),
    ]
