# Generated by Django 5.2 on 2025-08-19 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la configuración', max_length=100, verbose_name='Nombre de la clave')),
                ('description', models.TextField(blank=True, help_text='Explicación detallada del propósito de esta clave', null=True, verbose_name='Descripción')),
                ('config_key', models.CharField(help_text='Identificador único para esta configuración', max_length=100, verbose_name='Clave de configuración')),
                ('config_value', models.TextField(help_text='Valor asociado a esta clave de configuración', verbose_name='Valor de configuración')),
                ('status', models.BooleanField(default=True, help_text='Indica si la clave está activa (1) o inactiva (0)', verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_keys', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('system', models.ForeignKey(blank=True, db_column='system_id', help_text='Sistema al que pertenece esta clave (Odoo, Nubefact, SUNAT, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keys', to='systems.system', verbose_name='Sistema asociado')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_keys', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Clave de configuración',
                'verbose_name_plural': 'Claves de configuración',
                'db_table': 'keys',
                'ordering': ['system__name', 'config_key'],
                'constraints': [models.UniqueConstraint(fields=('system', 'config_key'), name='unique_system_config_key')],
            },
        ),
    ]
