# Generated by Django 5.2 on 2025-08-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'verbose_name': 'Clave de configuración', 'verbose_name_plural': 'Claves de configuración'},
        ),
        migrations.RemoveConstraint(
            model_name='key',
            name='unique_system_config_key',
        ),
    ]
