# Generated by Django 5.2 on 2025-08-21 20:14

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_birth_date_alter_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.employees.models.employee_image_upload_path),
        ),
    ]
