# Generated by Django 5.2 on 2025-08-21 22:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Lista de documentos en formato JSON'),
        ),
    ]
