# Generated by Django 5.2 on 2025-08-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
